/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package entornografico;
import clases.consultas;


/**
 *
 * @author alumno
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuProveedores = new javax.swing.JMenu();
        subListarProveedores = new javax.swing.JMenuItem();
        subInsertarProveedores = new javax.swing.JMenuItem();
        subInsertarProveedores1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/alumno/Cuidado-Cuando-Vas-de-Compras.jpg")); // NOI18N

        barraMenu.setName("barraMenu"); // NOI18N

        menuProveedores.setText("Proveedores");

        subListarProveedores.setText("Listar");
        subListarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subListarProveedoresActionPerformed(evt);
            }
        });
        menuProveedores.add(subListarProveedores);

        subInsertarProveedores.setText("Insertar");
        subInsertarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subInsertarProveedoresActionPerformed(evt);
            }
        });
        menuProveedores.add(subInsertarProveedores);

        subInsertarProveedores1.setText("Modificar");
        subInsertarProveedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subInsertarProveedores1ActionPerformed(evt);
            }
        });
        menuProveedores.add(subInsertarProveedores1);

        barraMenu.add(menuProveedores);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 711, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subListarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subListarProveedoresActionPerformed
       proveedores FormProveedores = new proveedores();
       FormProveedores.setVisible(true);
    }//GEN-LAST:event_subListarProveedoresActionPerformed

    private void subInsertarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subInsertarProveedoresActionPerformed
        // TODO add your handling code here:
        proveedoresinsertar FormInsertar = new proveedoresinsertar();
        FormInsertar.setVisible(true);
    }//GEN-LAST:event_subInsertarProveedoresActionPerformed

    private void subInsertarProveedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subInsertarProveedores1ActionPerformed

        proveedoresmodificar FormModificar = new proveedoresmodificar();
        FormModificar.setVisible(true);
    }//GEN-LAST:event_subInsertarProveedores1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu menuProveedores;
    private javax.swing.JMenuItem subInsertarProveedores;
    private javax.swing.JMenuItem subInsertarProveedores1;
    private javax.swing.JMenuItem subListarProveedores;
    // End of variables declaration//GEN-END:variables
}
