/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package entornografico;

import clases.consultas;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.*;
import java.io.*;
/**
 *
 * @author alumno
 */
public class amarres extends javax.swing.JFrame {

    /**
     * Creates new form amarres
     */
    public amarres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListAmarres = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jTFE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTCB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTCA = new javax.swing.JTextField();
        jTCM = new javax.swing.JTextField();
        jBReservar = new javax.swing.JButton();
        jBResetear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jBAtrasAmarrados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(jListAmarres);

        jLabel1.setText("*Fecha de Entrada:");

        jLabel2.setText("Fecha de Salida:");

        jLabel3.setText("*Codigo de Barco:");

        jTCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCBActionPerformed(evt);
            }
        });

        jLabel4.setText("*Codigo Amarre:");

        jLabel5.setText("*Codigo Muelle:");

        jBReservar.setText("Reservar");
        jBReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReservarActionPerformed(evt);
            }
        });

        jBResetear.setText("Resetear");
        jBResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResetearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Barcos Amarrados");

        jBAtrasAmarrados.setText("Atrás");
        jBAtrasAmarrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAtrasAmarradosMouseClicked(evt);
            }
        });
        jBAtrasAmarrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasAmarradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jBAtrasAmarrados))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTFE)
                                            .addComponent(jTFS)
                                            .addComponent(jTCB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jBReservar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTCA, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(jTCM)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jBResetear)))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jBAtrasAmarrados))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBReservar)
                    .addComponent(jBResetear))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            //controlador.controladorTurnos cc = new controlador.controladorTurnos();
            //DefaultListModel modelo = new DefaultListModel();
            DefaultListModel modelo = new DefaultListModel();
            consultas d = new consultas();
            ResultSet rs = null;
            rs=d.obtenerAmarres();  
            try {
                modelo.addElement("Fecha Entrada  ||  Fecha Salida  ||  C.Barco  ||  C.Amarre || C.Muelle");
                while(rs.next())
                {
                 modelo.addElement(rs.getDate("fechaEntrada")+"   ||   "+rs.getDate("fechaSalida")+"   ||    "+rs.getString("codigoBarco")+"    ||    "+rs.getString("idAmarre")+"    ||    "+rs.getString("idMuelle"));
                 jListAmarres.setModel(modelo);
                
                }
                                jListAmarres.setSelectedIndex(0);

            } catch (SQLException ex) {
                Logger.getLogger(empleadosinsertar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(empleadosinsertar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(empleadosinsertar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jBResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResetearActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        jTFE.setText("");
        jTFS.setText("");
        jTCB.setText("");
        jTCA.setText("");
        jTCM.setText("");
    }//GEN-LAST:event_jBResetearActionPerformed

    private void jBReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReservarActionPerformed
        // TODO add your handling code here:
/*
Mirar si o barco está introducido
*/
 if(jTFE.getText().equals("") ||  jTCB.getText().equals("") || jTCA.getText().equals("") || jTCM.getText().equals(""))
 {
  JOptionPane.showMessageDialog(null, "¡Por favor, rellene los campos obligatorios (los que tienen *)!", "¡Rellena los campos!", JOptionPane.INFORMATION_MESSAGE);
 }
 else
 {
      try {
    consultas d = new consultas();
    ResultSet rs = null;
    Integer codigo = Integer.parseInt(jTCB.getText());
    Integer codaux = null;
    rs=d.obtenerBarcosCodigo(codigo);  
    try {
        while(rs.next())
        {
         codaux=1;                
        }
         if(codaux==null) 
         { 
          JOptionPane.showMessageDialog(null, "¡Por favor, debido a que no tenemos dicho barco, introduzcalo en la base de datos o escoja otro barco!", "¡No hay barco!", JOptionPane.INFORMATION_MESSAGE);
         
         }
         
         else
         {
             
    DefaultListModel modelo = new DefaultListModel(); 
 try{
     d.reservaramarre(jTFE.getText(), jTFS.getText(), Integer.parseInt(jTCB.getText()), Integer.parseInt(jTCA.getText()), Integer.parseInt(jTCM.getText()));
     JOptionPane.showMessageDialog(null, "¡Reserva realizada correctamente! No hubo ningun tipo de problemas", "Reserva de amarre realizada", JOptionPane.INFORMATION_MESSAGE);
     this.dispose();
     amarres j = new amarres();
     j.setVisible(true);       
 }catch(Exception e)  
{  
e.printStackTrace();  
}            
             
   }
         
    } catch (SQLException ex) {
        Logger.getLogger(empleadosinsertar.class.getName()).log(Level.SEVERE, null, ex);
    }
    } catch (FileNotFoundException ex) {
    Logger.getLogger(empleadosinsertar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
    Logger.getLogger(empleadosinsertar.class.getName()).log(Level.SEVERE, null, ex);
    }  
        
      
 }
        
        
    }//GEN-LAST:event_jBReservarActionPerformed

    private void jBAtrasAmarradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasAmarradosActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBAtrasAmarradosActionPerformed

    private void jBAtrasAmarradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAtrasAmarradosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAtrasAmarradosMouseClicked
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amarres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amarres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amarres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amarres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amarres().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtrasAmarrados;
    private javax.swing.JButton jBReservar;
    private javax.swing.JButton jBResetear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jListAmarres;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCA;
    private javax.swing.JTextField jTCB;
    private javax.swing.JTextField jTCM;
    private javax.swing.JTextField jTFE;
    private javax.swing.JTextField jTFS;
    // End of variables declaration//GEN-END:variables
}
