/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package entornografico;
import clases.consultas;
import entornografico.empleados;


/**
 *
 * @author alumno
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuAmarres = new javax.swing.JMenu();
        subListarAmarres = new javax.swing.JMenuItem();
        subInsertarAmarres = new javax.swing.JMenuItem();
        subReservarAmarres = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();
        subListarEmpleados = new javax.swing.JMenuItem();
        subInsertarEmpleados = new javax.swing.JMenuItem();
        menuTurnos = new javax.swing.JMenu();
        subTurnos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/alumno/5049-PUERTO-ALICANTE-SATO-009-Large-21.JPG")); // NOI18N

        barraMenu.setName("barraMenu"); // NOI18N

        menuAmarres.setText("Amarres");

        subListarAmarres.setText("Listar");
        subListarAmarres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subListarAmarresActionPerformed(evt);
            }
        });
        menuAmarres.add(subListarAmarres);

        subInsertarAmarres.setText("Insertar");
        menuAmarres.add(subInsertarAmarres);

        subReservarAmarres.setText("Reservar");
        subReservarAmarres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subReservarAmarresActionPerformed(evt);
            }
        });
        menuAmarres.add(subReservarAmarres);

        barraMenu.add(menuAmarres);

        menuEmpleados.setText("Empleados");

        subListarEmpleados.setText("Listar");
        subListarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subListarEmpleadosActionPerformed(evt);
            }
        });
        menuEmpleados.add(subListarEmpleados);

        subInsertarEmpleados.setText("Insertar");
        subInsertarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subInsertarEmpleadosActionPerformed(evt);
            }
        });
        menuEmpleados.add(subInsertarEmpleados);

        barraMenu.add(menuEmpleados);

        menuTurnos.setText("Turnos");

        subTurnos.setText("Listar");
        subTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTurnosActionPerformed(evt);
            }
        });
        menuTurnos.add(subTurnos);

        barraMenu.add(menuTurnos);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTurnosActionPerformed
        //VTurnos Listado = new VTurnos();
        //Listado.setVisible(true);
    }//GEN-LAST:event_subTurnosActionPerformed

    private void subListarAmarresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subListarAmarresActionPerformed
    // TODO add your handling code here:
    
    }//GEN-LAST:event_subListarAmarresActionPerformed

    private void subInsertarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subInsertarEmpleadosActionPerformed

        empleadosinsertar FormEmpleadoss = new empleadosinsertar();
        FormEmpleadoss.setVisible(true);
        
        
    }//GEN-LAST:event_subInsertarEmpleadosActionPerformed

    private void subListarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subListarEmpleadosActionPerformed
        empleados FormEmpleados = new empleados();
        FormEmpleados.setVisible(true);
                
        /*
         *     private javax.swing.JButton jBInsertar;
    private javax.swing.JButton jBResetear;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JList jListEmpleados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTApellidos;
    private javax.swing.JTextField jTDNI;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTSueldo;
         * 
         * 
         * 
         */
        
        
    }//GEN-LAST:event_subListarEmpleadosActionPerformed

    private void subReservarAmarresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subReservarAmarresActionPerformed
        // TODO add your handling code here:
        amarres FormAmarres = new amarres();
        FormAmarres.setVisible(true);
    }//GEN-LAST:event_subReservarAmarresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu menuAmarres;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenu menuTurnos;
    private javax.swing.JMenuItem subInsertarAmarres;
    private javax.swing.JMenuItem subInsertarEmpleados;
    private javax.swing.JMenuItem subListarAmarres;
    private javax.swing.JMenuItem subListarEmpleados;
    private javax.swing.JMenuItem subReservarAmarres;
    private javax.swing.JMenuItem subTurnos;
    // End of variables declaration//GEN-END:variables
}
